/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VLayout: typeof import('vuetify/lib')['VLayout']
    VList: typeof import('vuetify/lib')['VList']
  }
}
