# Copyright (C) Lutra Consulting Limited
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-MerginMaps-Commercial

from flask import Flask

from .commands import add_commands
from .config import Configuration
from .db_events import register_events


def register(app: Flask):
    """Register mergin sync module in Flask app
    Adds Flask blueprint with autogenerated Flask/Connexion routes from openAPI definition.
    Register db events/hooks.
    """
    app.config.from_object(Configuration)

    app.connexion_app.add_api(
        "sync/public_api.yaml",
        arguments={"title": "Mergin"},
        options={"swagger_ui": False},
        validate_responses=True,
    )

    app.connexion_app.add_api(
        "sync/public_api_v2.yaml",
        arguments={"title": "Mergin"},
        options={"swagger_ui": False},
        validate_responses=True,
    )

    app.connexion_app.add_api(
        "sync/private_api.yaml",
        base_path="/app",
        arguments={"title": "Mergin"},
        options={"swagger_ui": False, "serve_spec": False},
        validate_responses=True,
    )

    add_commands(app)
    register_events()
