/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDataFooter: typeof import('vuetify/lib')['VDataFooter']
    VDataTable: typeof import('vuetify/lib')['VDataTable']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VLayout: typeof import('vuetify/lib')['VLayout']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
