/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PAvatar: typeof import('primevue/avatar')['default']
    PButton: typeof import('primevue/button')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PInputSwitch: typeof import('primevue/inputswitch')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PPassword: typeof import('primevue/password')['default']
    PTabPanel: typeof import('primevue/tabpanel')['default']
    PTabView: typeof import('primevue/tabview')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
