
networks:
  merginmaps:
    name: mergin

services:
  db:
    image: postgres:14
    container_name: merginmaps-db
    restart: always
    networks:
      - merginmaps
    environment:
      - POSTGRES_DB=mergin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # !TODO Change this and also change .prod.env $DB_PASSWORD accordingly
    volumes:
      - ./mergin_db:/var/lib/postgresql/data
  redis:
    image: redis:6.2.17
    container_name: merginmaps-redis
    restart: always
    networks:
      - merginmaps
  server:
    image: lutraconsulting/merginmaps-backend:2025.7.3
    container_name: merginmaps-server
    restart: always
    user: 901:999
    volumes:
      - ./projects:/data
      - ./diagnostic_logs:/diagnostic_logs
    env_file:
      - .prod.env
    depends_on:
      - db
      - redis
    command: [ "gunicorn --config config.py application:application" ]
    networks:
      - merginmaps
  celery-beat:
    image: lutraconsulting/merginmaps-backend:2025.7.3
    container_name: celery-beat
    restart: always
    env_file:
      - .prod.env
    environment:
      - GEVENT_WORKER=0
      - NO_MONKEY_PATCH=1
    depends_on:
      - redis
      - server
    command: [ "celery -A application.celery beat --loglevel=info" ]
    networks:
      - merginmaps
  celery-worker:
    image: lutraconsulting/merginmaps-backend:2025.7.3
    container_name: celery-worker
    restart: always
    user: 901:999
    env_file:
      - .prod.env
    environment:
      - GEVENT_WORKER=0
      - NO_MONKEY_PATCH=1
    volumes:
      - ./projects:/data
    depends_on:
      - redis
      - server
      - celery-beat
    command: [ "celery -A application.celery worker --loglevel=info" ]
    networks:
      - merginmaps
  web:
    image: lutraconsulting/merginmaps-frontend:2025.7.3
    container_name: merginmaps-web
    restart: always
    depends_on:
      - server
    user: 101:999
    links:
      - db
    networks:
      - merginmaps
  proxy:
    image: nginxinc/nginx-unprivileged:1.27
    container_name: merginmaps-proxy
    restart: always
    # run nginx as built-in user but with group mergin-family for files permissions
    user: 101:999
    ports:
      - "8080:8080"
    volumes:
      - ./projects:/data  # mergin maps projects data dir to host
      - ../common/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - merginmaps
