"""add mergin statistics table

Revision ID: 37cf462d76ed
Revises: d02961c7416c
Create Date: 2025-01-22 17:09:00.718129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37cf462d76ed'
down_revision = 'd02961c7416c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mergin_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mergin_statistics'))
    )
    op.create_index(op.f('ix_mergin_statistics_created_at'), 'mergin_statistics', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mergin_statistics_created_at'), table_name='mergin_statistics')
    op.drop_table('mergin_statistics')
    # ### end Alembic commands ###
