"""Add project version changes

Revision ID: 4f54ee8c4acd
Revises: bd1ec73db389
Create Date: 2025-10-01 11:49:13.560320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f54ee8c4acd'
down_revision = 'bd1ec73db389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_version_changes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['project_version.id'], name=op.f('fk_project_version_changes_version_id_project_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_version_changes')),
    sa.UniqueConstraint('version_id', 'rank', name='unique_changes')
    )
    op.create_index('ix_project_version_change_version_id_rank', 'project_version_changes', ['version_id', 'rank'], unique=False)
    op.create_index(op.f('ix_project_version_changes_rank'), 'project_version_changes', ['rank'], unique=False)
    op.create_index(op.f('ix_project_version_changes_version_id'), 'project_version_changes', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_version_changes_version_id'), table_name='project_version_changes')
    op.drop_index(op.f('ix_project_version_changes_rank'), table_name='project_version_changes')
    op.drop_index('ix_project_version_change_version_id_rank', table_name='project_version_changes')
    op.drop_table('project_version_changes')
    # ### end Alembic commands ###
