"""Add project version changes

Revision ID: 63adc90fca0c
Revises: bd1ec73db389
Create Date: 2025-10-01 16:50:08.343639

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "63adc90fca0c"
down_revision = "bd1ec73db389"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_version_change",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("delta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_version.id"],
            name=op.f("fk_project_version_change_version_id_project_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_version_change")),
        sa.UniqueConstraint("version_id", "rank", name="unique_changes"),
    )
    op.create_index(
        op.f("ix_project_version_change_rank"),
        "project_version_change",
        ["rank"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_version_change_version_id"),
        "project_version_change",
        ["version_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_version_change_version_id_rank",
        "project_version_change",
        ["version_id", "rank"],
        unique=False,
    )
    # ### end Alembic commands ###

    # data migration
    op.execute(
        """
        INSERT INTO project_version_change (version_id, rank, delta)
        SELECT
            h.version_id,
            0 AS rank,
            jsonb_agg(
                jsonb_strip_nulls(
                    jsonb_build_object(
                        'path', fp.path,
                        'size', h.size,
                        'change', h.change,
                        'version', 'v' || h.project_version_name,
                        'checksum', h.checksum,
                        'diff', fdj.diff_path
                    )
                )
            ) AS delta
        FROM
            file_history h
        JOIN
            project_file_path fp ON h.file_path_id = fp.id
        LEFT JOIN LATERAL (
            SELECT
                fd.path AS diff_path
            FROM
                file_diff fd
            WHERE
                fd.file_path_id = fp.id
                AND fd.version = h.project_version_name
                AND fd.rank = 0
        ) fdj ON TRUE
        GROUP BY
            h.version_id;
    """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_project_version_change_version_id_rank", table_name="project_version_change"
    )
    op.drop_index(
        op.f("ix_project_version_change_version_id"),
        table_name="project_version_change",
    )
    op.drop_index(
        op.f("ix_project_version_change_rank"), table_name="project_version_change"
    )
    op.drop_table("project_version_change")
    # ### end Alembic commands ###
