"""Add project version delta

Revision ID: 9acf967e58ad
Revises: bd1ec73db389
Create Date: 2025-10-10 17:33:31.740232

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9acf967e58ad"
down_revision = "bd1ec73db389"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_version_delta",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_version.id"],
            name=op.f("fk_project_version_delta_version_id_project_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_version_delta")),
        sa.UniqueConstraint("version_id", "rank", name="unique_deltas"),
    )
    op.create_index(
        op.f("ix_project_version_delta_rank"),
        "project_version_delta",
        ["rank"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_version_delta_version_id"),
        "project_version_delta",
        ["version_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_version_delta_version_id_rank",
        "project_version_delta",
        ["version_id", "rank"],
        unique=False,
    )
    # ### end Alembic commands ###

    # data migration
    op.execute(
        """
        INSERT INTO project_version_delta (version_id, rank, changes)
        SELECT
            h.version_id,
            0 AS rank,
            jsonb_agg(
                jsonb_strip_nulls(
                    jsonb_build_object(
                        'path', fp.path,
                        'size', h.size,
                        'change', h.change,
                        'version', h.project_version_name,
                        'checksum', h.checksum,
                        'diff', fdj.diff_path
                    )
                )
            ) AS changes
        FROM
            file_history h
        JOIN
            project_file_path fp ON h.file_path_id = fp.id
        LEFT JOIN LATERAL (
            SELECT
                fd.path AS diff_path
            FROM
                file_diff fd
            WHERE
                fd.file_path_id = fp.id
                AND fd.version = h.project_version_name
                AND fd.rank = 0
        ) fdj ON TRUE
        GROUP BY
            h.version_id;
    """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_project_version_delta_version_id_rank", table_name="project_version_delta"
    )
    op.drop_index(
        op.f("ix_project_version_delta_version_id"), table_name="project_version_delta"
    )
    op.drop_index(
        op.f("ix_project_version_delta_rank"), table_name="project_version_delta"
    )
    op.drop_table("project_version_delta")
    # ### end Alembic commands ###
