networks:
  mergin-net:
    external: true
    name: mergin-ee

services:
  qgis:
    container_name: mergin-qgis
    image: 433835555346.dkr.ecr.eu-west-1.amazonaws.com/mergin/qgis-server-ee:2025.1.0
    user: 1000:999
    networks:
      - mergin-net
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=false
      - QGIS_SERVER_MAX_THREADS=-1
      - QGIS_SERVER_WMS_MAX_HEIGHT=1536
      - QGIS_SERVER_WMS_MAX_WIDTH=1536
    volumes:
      - ./overviews/projects:/overviews/projects
  qgis_nginx:
    container_name: mergin-qgis-nginx
    image: nginxinc/nginx-unprivileged:1.27
    user: 101:999
    networks:
      - mergin-net
    depends_on:
      - qgis
    #volumes:
    #  - ./qgis_nginx_nginx-conf:/etc/nginx/conf.d/default.conf
  qgis_extractor:
    container_name: mergin-qgis-extractor
    image: 433835555346.dkr.ecr.eu-west-1.amazonaws.com/mergin/qgis-extractor-ee:2025.1.0
    user: 901:999
    networks:
      - mergin-net
    environment:
      - OVERVIEWS_DATA_DIR=/data
      - MM_WMS_TILE_BUFFER=100
      - MM_WMS_AVOID_ARTIFACTS=1
    volumes:
      - ./overviews/projects:/data
