name: mergin-enterprise
networks:
  mergin:
    name: mergin-ee

services:
  server:
    image: 433835555346.dkr.ecr.eu-west-1.amazonaws.com/mergin/mergin-ee-back:2025.5.1
    container_name: merginmaps-server
    restart: always
    user: 901:999
    command: ["gunicorn -w 4 --config config.py application:application"]
    volumes:
      - ./data:/data  # map data dir to host
      - ./diagnostic_logs:/diagnostic_logs # diagnostic logs dir
    env_file:
      - .prod.env
    environment:
      - GUNICORN_CMD_ARGS="--limit-request-line 8190"
    depends_on:
      - db
    networks:
      - mergin
  web:
    image: 433835555346.dkr.ecr.eu-west-1.amazonaws.com/mergin/mergin-ee-front:2025.5.1
    container_name: merginmaps-web
    restart: always
    depends_on:
      - server
    env_file:
      - .prod.env
    networks:
      - mergin
  proxy:
    image: nginxinc/nginx-unprivileged:1.27
    container_name: merginmaps-proxy
    restart: always
    # run nginx as built-in user but with group mergin-family for files permissions
    user: 101:999
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/data  # map data dir to host
      - ../common/nginx.conf:/etc/nginx/templates/default.conf.template
      # If using sso, uncomment the next line
      # - ./sso/sso-nginx.conf:/etc/nginx/templates/sso.conf.template
    networks:
      - mergin
    depends_on:
      - web
      - server

  celery-beat:
    image: 433835555346.dkr.ecr.eu-west-1.amazonaws.com/mergin/mergin-ee-back:2025.5.1
    container_name: merginmaps-celery-beat
    restart: always
    user: 901:999
    command: ["celery -A application.celery beat --loglevel=info"]
    env_file:
      - .prod.env
    depends_on:
      - db
      - redis
    networks:
      - mergin

  celery-worker:
    image: 433835555346.dkr.ecr.eu-west-1.amazonaws.com/mergin/mergin-ee-back:2025.5.1
    container_name: merginmaps-celery-worker
    restart: always
    user: 901:999
    command: ["celery -A application.celery worker --pool prefork --loglevel=info"]
    volumes:
      - ./data:/data  # map data dir to host
      - ./map_data:/overviews
    env_file:
      - .prod.env
    depends_on:
      - db
      - redis
    networks:
      - mergin
  db:
    image: postgres:14
    container_name: merginmaps-db
    restart: always
    volumes:
      - ./mergin-db-enterprise:/var/lib/postgresql/data
      - ./sso/boxy.sql:/docker-entrypoint-initdb.d/boxy.sql
    environment:
      - POSTGRES_DB=mergin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # !TODO Change this and also change .prod.env $DB_PASSWORD accordingly
    networks:
      - mergin
  redis:
    image: redis
    container_name: merginmaps-redis
    restart: always
    networks:
      - mergin
