networks:
  mergin:
    name: mergin-ee

services:
  jackson:
    image: boxyhq/jackson:1.45.3
    container_name: merginmaps-sso
    restart: always
    volumes:
      - ./sso/sso-connections:/sso-connections
    env_file:
      - .sso.env
    networks:
      - mergin
    ports:
      - 5225:5225
