networks:
  mergin:
    name: mergin-ee

services:
  sso-server:
    image: boxyhq/jackson:1.45.3
    container_name: merginmaps-sso-server
    restart: always
    env_file:
      - .sso.env
    networks:
      - mergin # If you plan to deploy SSO stack on an isolated machine, just comment out this
