/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PAccordion: typeof import('primevue/accordion')['default']
    PAccordionTab: typeof import('primevue/accordiontab')['default']
    PAutoComplete: typeof import('primevue/autocomplete')['default']
    PAvatar: typeof import('primevue/avatar')['default']
    PBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PButton: typeof import('primevue/button')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDataView: typeof import('primevue/dataview')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PDivider: typeof import('primevue/divider')['default']
    PDropdown: typeof import('primevue/dropdown')['default']
    PImage: typeof import('primevue/image')['default']
    PInlineMessage: typeof import('primevue/inlinemessage')['default']
    PInputSwitch: typeof import('primevue/inputswitch')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenu: typeof import('primevue/menu')['default']
    PMenubar: typeof import('primevue/menubar')['default']
    PMessage: typeof import('primevue/message')['default']
    POverlayPanel: typeof import('primevue/overlaypanel')['default']
    PPanel: typeof import('primevue/panel')['default']
    PPassword: typeof import('primevue/password')['default']
    PProgressBar: typeof import('primevue/progressbar')['default']
    PProgressSpinner: typeof import('primevue/progressspinner')['default']
    PSidebar: typeof import('primevue/sidebar')['default']
    PSkeleton: typeof import('primevue/skeleton')['default']
    PTabPanel: typeof import('primevue/tabpanel')['default']
    PTabView: typeof import('primevue/tabview')['default']
    PTag: typeof import('primevue/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
