/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAutocomplete: typeof import('vuetify/lib')['VAutocomplete']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VBtnToggle: typeof import('vuetify/lib')['VBtnToggle']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDataIterator: typeof import('vuetify/lib')['VDataIterator']
    VDataTable: typeof import('vuetify/lib')['VDataTable']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VForm: typeof import('vuetify/lib')['VForm']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VChip: typeof import('vuetify/lib')['VChip']
    VChipGroup: typeof import('vuetify/lib')['VChipGroup']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VLayout: typeof import('vuetify/lib')['VLayout']
    VList: typeof import('vuetify/lib')['VList']
    VListGroup: typeof import('vuetify/lib')['VListGroup']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VPagination: typeof import('vuetify/lib')['VPagination']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VResponsive: typeof import('vuetify/lib')['VResponsive']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsSlider: typeof import('vuetify/lib')['VTabsSlider']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
