openapi: 3.0.0
info:
  description: Statistics Mergin Maps API
  version: "0.1"
  title: Statistics Mergin Maps API
servers:
  - url: /
paths:
  /app/admin/report:
    get:
      summary: Download statistics for server
      operationId: download_report
      x-openapi-router-controller: mergin.stats.controller
      parameters:
        - name: date_from
          in: query
          description: Start date for statistics (YYYY-MM-DD)
          required: true
          schema:
            type: string
            format: date
        - name: date_to
          in: query
          description: End date for statistics (YYYY-MM-DD)
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: CSV file with statistics
          content:
            text/csv:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequestResp"
        "404":
          $ref: "#/components/responses/NotFoundResp"
components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid.
    NotFoundResp:
      description: Project not found.
    BadRequestResp:
      description: Invalid request.
