name: Auto Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - suite: server
            pytest_args: "-v --cov=mergin --cov-report=lcov mergin/tests"
          - suite: migration
            pytest_args: "-v mergin/test_migrations"

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5435:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5435

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          cd server
          sudo apt-get -y install libsqlite3-mod-spatialite
          pip install pipenv==2026.0.3
          pipenv install --dev --verbose --python 3.12

      - name: Run tests
        run: |
          cd server
          pipenv run pytest ${{ matrix.pytest_args }}

      - name: Coveralls
        if: matrix.suite == 'server'
        uses: coverallsapp/github-action@v2
        with:
          base-path: server
          format: lcov
