name: Code Layout

on: push

jobs:
  code_style_python:
    name: Python code convention check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: psf/black@stable
        with:
          version: 25.1.0
          options: "--check --verbose --diff"
          src: "./server"

  code_style_js:
    name: JavaScript code convention check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Check JS
        run: |
            cd web-app
            yarn install
            yarn run lint:no-legacy
