name: Code Layout

on:
  push:
    paths:
      # Run just when python files changed
      - "server/**/*.py"
      - ".github/workflows/code_style.yml"

jobs:
  code_style_python:
    name: Python code convention check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: psf/black@stable
        with:
          version: 25.1.0
          options: "--check --verbose --diff"
          src: "./server"
